### ISSUE TITLE
Pseudo Residuals for multivariate normal emission distribution.

### ISSUE THREAD

**Issue by threex1ng** [bmcclintock/momentuHMM#36]
Hi Brett,

I am trying to compute pseudo residuals for HMM assuming bivariate Gaussian as emission distribution. I noticed that you made use of the Mahalanobis distance to compute the cumulative density function for bivariate Gaussian (mvnorm2). So that the cumulative probability and pseudo residual can be calculated for each time t. 
There are two kinds of pseudo-residual, one is uniform pseudo-residual and the other is normal pseudo-residual according to Zucchini et al book.

However, in your code for pseudoRes function:
if(dist[[j]] %in% mvndists){
          genRes[[paste0(j,"Res")]][i] <- stats::qchisq(genRes[[paste0(j,"Res")]][i],df=ndim)
        }
it seems that you assumed the pseudo-residuals are distributed Chi-squared with ndim degree of freedom instead of Normal.
May I know the reason why you choose qchisq?
Thank you for your useful package and look forward to your reply.

Bests,
Jiaxing

**Comment by bmcclintock** [comment]
Hi Jiaxing,

Good question! The short answer is that the squared Mahalanobis distance of a multivariate Gaussian distribution is Chi-Square distributed. Markus Thill has written a very nice [post](https://markusthill.github.io/mahalanbis-chi-squared/) on this.

Cheers,
Brett
