### ISSUE TITLE
Error: argument "theta" is missing with no default

### ISSUE THREAD

**Issue by matt-needle** [bmcclintock/momentuHMM#58]
When working through the grey seal example, running the `crawlWrap()` function

```
crwOut<-crawlWrap(greySealData,err.model=list(x=~ln.sd.x-1,y=~ln.sd.y-1,rho=~error.corr),
                   fixPar=c(1,1,NA,NA),attempts=100,retryFits=20,
                   timeStep="2 hours")

Fitting 1 track(s) using crawl::crwMLE... 
```

returns the error:

```
Error in get(s, env, inherits = FALSE) : 
  argument "theta" is missing, with no default
```

**Comment by bmcclintock** [comment]
It looks like you're using old versions of `crawl` and/or `momentuHMM` (before default values for the `theta` argument were provided by `crawl::crwMLE`). Reinstall/update the `crawl` package. Then reinstall `momentuHMM`.

**Comment by matt-needle** [comment]
Hi Brett,

Thank you for your fast reply. I was out of office for a couple of days, hence my slow reaction. According to RStudio, I have the latest version of both packages (installed from CRAN - perhaps there are later source versions available).

The problem persists. A workaround is to add `theta=c(1,1)` which results in a reasonable looking CRAWL prediction, but this is purely arbitrary. I have no reasoning for using 1 and I have no idea if 1 is approporiate in this case. Using `theta=c(NA,NA)` resulted in an error and the `crwMLE` function failed.

Unfortunately, there is not a single mention of it in this text: https://jmlondon.github.io/crawl-workshop/crawl-practical.html#preparing-input-data-for-crawl

I have just found your answer to [this issue](https://github.com/bmcclintock/momentuHMM/issues/28), where you suggest trying many different starting values. I will adopt a similar approach to choosing `Par0` values in [this guide](https://cran.r-project.org/web/packages/moveHMM/vignettes/moveHMM-starting-values.pdf).

Kind regards,

Matt

**Comment by bmcclintock** [comment]
Hmm I'd double check that the packages have actually been updated. Either way, I'm glad you've found what appears to be a solution. FWIW, zero is the default value for all values of `theta` in `crawl::crwMLE`.

**Comment by matt-needle** [comment]
I see the generation of the `theta` argument in the source code for `checkCrawlArgs` which should be called by the `crawlWrap` function but for some reason it is being overlooked by my setup. Perhaps a clean re-install would solve it my end but for now I will add the `theta` argument manually.

```else {
        theta <- list()
        for (i in ids) {
            theta[[i]] <- rep(0, sum(is.na(fixPar[[i]])))
        }
    }
```

Thank you for the 0 value tip! I also just found that in the documentation for `crawlWrap`, whereas I was searching before in the `crwMLE` docs and they are much less descriptive.

I am new to movement ecology and HMMS. Getting my head around all these inputs is quite overwhelming. Thank you for taking time to answer, and thanks for a great package!
