### ISSUE TITLE
Modelling pitch

### ISSUE THREAD

**Issue by theoniphotopoulou** [bmcclintock/momentuHMM#91]
Hi Brett,

I've come back to some old code where I'm modelling step length, pitch and yaw and my previous code doesn't seem to be working anymore. It works fine if I model just step and yaw, but it really doesn't like pitch, and won't model it even on its own. The data for pitch seem fine, they are well within -pi and pi. 

The error I get is this:
```
> mNULL_exp1_2st <- momentuHMM:::fitHMM(data = exp1prep, nbStates=2, 
                                   dist = list(step = 'gamma', pitch = 'wrpcauchy', yaw = 'wrpcauchy'),
                                   Par0 = list(step = stepPar0, pitch = PanglePar0, yaw = YanglePar0),
                                   stateNames = stateNames)
Error in get_fixParIndex(Par0, beta0, delta0, fixPar, distnames, inputs,  : fixPar$pi must be of length 1
```

Any idea what this error message means? 

The reason I came back to this code is because I have some new data to feed through the analysis, but I can't get the code to run with the old data either. I updated R and downloaded the latest version of momentuHMM but I can't figure out what has changed and what I need to do differently now.

Any help would be hugely appreciated!

Many thanks,
Theoni

**Comment by bmcclintock** [comment]
This is definitely a bug that got introduced when discrete random effects were added to `momentuHMM` v1.5.0. The `get_fixParIndex` function is trying to extract any `fixPar` values for the mixture probability parameter `pi`, but one of your data stream names (`pitch`) begins with 'pi'. I've added some checks for data stream names and changed all instances of `$pi` to `[["pi"]]`. I suppose you could just change the name of the `pitch` data stream, but these fixes are now in the 'develop' branch:
```
> remotes::install_github('bmcclintock/momentuHMM@develop')
```
and will be included in the next CRAN release (>=v1.5.3)
