### ISSUE TITLE
crawlWrap function requires fixPar and theta argument and has no default on Windows only

### ISSUE THREAD

**Issue by mebowers5** [bmcclintock/momentuHMM#94]
In the previous version of momentuHMM, I used "initial.state = ..." in my crawlWrap code. 

```
firsts <- aggregate(as.numeric(row.names(daily_locs)), list(daily_locs$ID), min)$x

get_init <- function(x){
     out <- c(daily_locs$x[x],0, daily_locs$y[x],0)
     return(out)
}
inits <- lapply(firsts, get_init)

crw_mod <- crawlWrap(obsData = daily_locs, timestep = "15 min", initial.state = inits,
                                        attempts = 15, retryFits = 20)
```
However, in the recent release, initial.state has been removed and fixPar and theta arguments are required - apparently only on Windows (runs fine on Mac and Linux). 

This code also runs correctly on my Windows OS:
`crawl::crwMLE(data=subset(daily_locs, ID==1), attempts = 15)`

Fix: The code runs fine with fixPar = c(NA, NA) and theta = c(0,0) 

`crw_mod <- crawlWrap(obsData = daily_locs, timestep = "15 min", fixPar = c(NA, NA), theta = c(0,0),
                                          attempts = 15, retryFits = 20)`

**Comment by bmcclintock** [comment]
It appears Windows won't permit missing arguments in a calling function to be exported when using foreach, even if the expression doesn't use or require those missing arguments. Fixed in 4344a17278f890618ab4a6d448818781d4f1c93f for inclusion in future releases (>=1.5.3)
